# 基本优化结束
custom_css:
  toc_smooth: true
  cursor:
    enable: true
    text: https://cdn.jsdelivr.net/gh/sakurasep/main-cdn@2.0/Volantis/Other/cursor/text.png
    pointer: https://cdn.jsdelivr.net/gh/sakurasep/main-cdn@2.0/Volantis/Other/cursor/pointer.png
    default: https://cdn.jsdelivr.net/gh/sakurasep/main-cdn@2.0/Volantis/Other/cursor/left_ptr.png
    not-allowed: https://cdn.jsdelivr.net/gh/sakurasep/main-cdn@2.0/Volantis/Other/cursor/circle.png
    zoom-out: https://cdn.jsdelivr.net/gh/sakurasep/main-cdn@2.0/Volantis/Other/cursor/zoom-out.png
    zoom-in: https://cdn.jsdelivr.net/gh/sakurasep/main-cdn@2.0/Volantis/Other/cursor/zoom-in.png
    grab: https://cdn.jsdelivr.net/gh/sakurasep/main-cdn@2.0/Volantis/Other/cursor/openhand.png
  scrollbar:
    size: 4px
    border: 2px  
  fontsize:
    root: 16px
    footnote: .78rem
  navbar:
    height: 64px
    width: auto
    effect: [floatable]
  sidebar:
    effect: [floatable]
  body:
    effect: [floatable]
  fontfamily:
    logofont:
      fontfamily: 'MaShanZheng, Roboto, Noto Serif SC,-apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif'
      url: ''
    bodyfont:
      fontfamily: '"Noto Serif SC", Roboto,-apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif'
      url: ''
    codefont:
      fontfamily: 'JetBrainsMono, Menlo,Monaco,Consolas,Andale Mono,lucida console,Courier New,monospace'
      url: ''
#基本优化结束
color_scheme:
  common:
    selection: '#ddf4ff'
  light:
    site_bg: '#f7f9fe'
    meta: '#666'
    site_footer: '#fff'
  dark:
    site_bg: '#21252b'
    site_footer: '#abb2bf'
    card: '#282c34'
    text: '#abb2bf'
    block: '#21252b'
    h1: '#979fa-duotone'
    h2: '#979fa-duotone'
    h3: '#979fa-duotone'
    h4: '#979fa-duotone'
    h5: '#979fa-duotone'
    h6: '#979fa-duotone'
    p: '#abb2bf'

# 右键菜单
rightmenu:
  enable: false
  faicon: fal PETERRIVE
  layout: [copy, navigation, hr, source_docs, friends, text, about, hr, print, reading, darkmode, hr, music]
  print:                
    name: 打印页面
    icon: fal fa-print TURQUOISE
    defaultStyles: true   
    js:                 
      - document.querySelector('article#comments').remove()
  darkmode:
    name: 暗黑模式
    icon: fal fa-moon WISTERIA
  reading:
    name: 阅读模式
    icon: fal fa-book-open EMERALD
  customPicUrl:    
    enable: false 
    old: 
    new: 
  music:          
    alwaysShow: true
  friends:
    name: 我的朋友们
    icon: fal fa-flower-daffodil AMETHYST
    url: /friends/
  examples:
    name: 我的团队
    icon: fal fa-book-open CARROT
    url: https://sakurasep.club/
  source_docs:
    name: 本站源码
    icon: fal fa-code-branch SUNFLOWER
    url: httsp://github.com/sakurasep
  text:
    name: 文章归档
    icon: fal fa-globe-asia CONCRETE
    url: /archives/
  about:
    name: 关于我
    icon: fal fa-gingerbread-man WISTERIA
    url: /about/

rightmenus:
  enable: true
  order: 
    - plugins.navigation
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - plugins.elementCheck
    - plugins.elementImage
    - menus.link
    - hr
    - menus.darkMode
    - plugins.articlePage
    - music
  options:
    iconPrefix: fa-duotone PETERRIVE
    articleShowLink: true
  plugins:
    navigation: 
      - {id: 'left', name: '转到上一页', icon: 'fa-duotone fa-arrow-left PETERRIVE', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: '转到下一页', icon: 'fa-duotone fa-arrow-right PETERRIVE', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: '刷新当前页面', icon: 'fa-duotone fa-redo PETERRIVE', event: 'window.location.reload()', group: 'navigation'}
      - {id: 'up', name: '回到顶部', icon: 'fa-duotone fa-arrow-up PETERRIVE', event: 'VolantisApp.scrolltoElement(volantis.dom.bodyAnchor)', group: 'navigation'}
      - {id: 'home', name: '回到首页', icon: 'fa-duotone fa-home PETERRIVE', link: '/', group: 'navigation'}
    inputBox:
      - {id: 'copyPaste', name: '粘贴文本', icon: 'fa-duotone PETERRIVE fa-paste', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: '全选文本', icon: 'fa-duotone PETERRIVE fa-object-ungroup', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: '剪切文本', icon: 'fa-duotone PETERRIVE fa-cut', event: 'copyCut', group: 'inputBox'} 
    seletctText:
      - {id: 'copyText', name: '复制文本', icon: 'fa-duotone PETERRIVE fa-copy', event: 'copyText', group: 'seletctText'}
      - {id: 'searchWord', name: '站内搜索', icon: 'fa-duotone PETERRIVE fa-search', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'bingSearch', name: '必应搜索', icon: 'fa-duotone PETERRIVE fa-search', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText'}
    elementCheck:
      - {id: 'openTab', name: '新标签页打开', icon: 'fa-duotone PETERRIVE fa-external-link-square-alt', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: '复制链接地址', icon: 'fa-duotone PETERRIVE fa-link', event: 'copyLink', group: 'elementCheck'}
      - {id: 'copyImg', name: '复制图片文件', icon: 'fa-duotone PETERRIVE fa-image', event: 'copyImg', group: 'elementCheck'}
    elementImage:
      - {id: 'copyImg', name: '复制图片', icon: 'fa-solid fa-image', event: 'copyImg', group: 'elementImage'}
      - {id: 'googleImg', name: '谷歌识图', icon: 'fa-solid fa-images', event: 'window.open(`https://www.google.com.hk/searchbyimage?image_url=${__link__}`)', group: 'elementImage'}
    articlePage:
      - {id: 'printMode', name: '打印页面', icon: 'fa-duotone fa-print TURQUOISE', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: '阅读模式', icon: 'fa-duotone fa-book-open EMERALD', event: 'readMode', group: 'articlePage'}
# 右键自定义菜单区域
  menus:
    link:
      - {id: 'github', name: '本站源码', icon: 'fa-duotone fa-code-branch SUNFLOWER', link: 'https://github.com/sakurasep', group: 'link'}
      - {id: 'friends', name: '我的朋友们', icon: 'fa-duotone fa-flower-daffodil AMETHYST', link: '/friends/', group: 'link'}
      - {id: 'archive', name: '文章归档', icon: 'fa-duotone fa-globe-asia CONCRETE', link: '/archives/', group: 'link'}
      - {id: 'about', name: '关于我', icon: 'fa-duotone fa-gingerbread-man WISTERIA', link: '/about/', group: 'link'}
    darkMode: 
      - {id: 'darkMode', name: '暗黑模式', icon: 'fa-duotone fa-eclipse-alt WISTERIA', event: 'volantis.dark.toggle()', group: 'darkMode'}

# 导航栏
navbar:
  visiable: auto
  logo:
    img: 
    icon: 
    title: 上杉九月的博客
  search: 搜索你想知道的内容
  menu:
    - name: 首页
      icon: fa-light fa-home SUNFLOWER faa-vertical
      url: /
    - name: 分站
      icon: fa-light fa-rss CARROT faa-vertical
      rows:
        - name: Shoka
          url: Shoka/
        - name: Butterfly
          url: Butterfly/
        - name: Matery
          url: Matery/
        - name: Fluid
          url: Fluid/
        - name: Yun
          url: Yun/
    - name: 文章
      icon: fa-light fa-book-reader GREENSEA faa-vertical
      rows:
        - name: 分类
          icon: fa-light fa-folder-open TURQUOISE faa-vertical
          url: categories/
        - name: 标签
          icon: fa-light fa-tags PETERRIVE faa-vertical
          url: tags/
        - name: 归档
          icon: fa-light fa-archive GREENSEA faa-vertical
          url: archives/
    - name: 导航
      icon: fa-light fa-cube NEPHRITIS faa-vertical
      rows:
        - name: 关于
          icon: fa-light fa-info-circle SUNFLOWER faa-vertical
          url: about/
        - name: 留言板
          icon: fa-light fa-comment-alt-dots GREENSEA faa-vertical
          url: info/
        - name: hr
        - name: 追番
          icon: fa-light fa-video EMERALD faa-vertical
          url: bangumis/
        - name: 追剧
          icon: fa-light fa-video EMERALD faa-vertical
          url: cinemas/
        - name: hr
        - name: 友链
          icon: fa-light fa-link POMEGRANATE faa-vertical
          url: friends/
        - name: 朋友的文章
          icon: fa-light fa-user-friends ALIZARIN faa-vertical
          url: fcircle/
        - name: hr
        - name: BBTalk
          icon: fa-light fa-comments PETERRIVE faa-vertical
          url: bb/  
        - name: ArtiTalk
          icon: fa-light fa-comments PETERRIVE faa-vertical
          url: artitalk/
    - name: 功能
      icon: fa-light fa-tools ALIZARIN faa-vertical
      rows:
        - name: 深色模式
          icon: fa-light fa-moon POMEGRANATE faa-vertical
          toggle: darkmode
        - name: 背景音乐
          icon: fa-light fa-compact-disc EMERALD faa-vertical
        - name: hr  
        - name: RSS 订阅
          icon: fa-light fa-rss SUNFLOWER faa-vertical
          url: atom.xml
        - name: 网站运行状态
          icon: fa-light fa-user-clock PETERRIVE faa-vertical
          url: https://stats.uptimerobot.com/jJZj1SjwDJ
    - name: 更多 # 可自定义
      icon: fa-light fa-compass WISTERIA faa-vertical # 可自定义
      rows: 
        - name: Typecho
          icon: fa-light fa-blog POMEGRANATE faa-vertical
          url: https://blog.sakurasep.club/
        - name: Halo
          icon: fa-light fa-blog ALIZARIN faa-vertical
          url: https://halo.sakurasep.club/
        - name: hr
        - name: Chevereto
          icon: fa-light fa-images EMERALD faa-vertical
          url: https://pic.sakurasep.top/
        - name: Oneindex
          icon: fa-light fa-images SUNFLOWER faa-vertical
          url: https://pic.sakurasep.club/
        - name: Cloudreve
          icon: fa-light fa-browser PETERRIVE faa-vertical
          url: https://cloud.sakurasep.club/
    - name: 开往
      icon: fa-light fa-subway PETERRIVE faa-ring faa-slow
      url: https://travellings.link

# 网站页脚
site_footer:
  layout: [aplayer, social, lic, cpy, me, icp]
  social:
    - img: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/020-rss.svg
      url: atom.xml
    - img: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/029-github.svg
      url: https://github.com/sakurasep
    - img: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/012-blogger.svg
      url: https://blog.sakurasep.club
    - img: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/006-youtube.svg
      url: https://www.youtube.com/channel/UCTJn92N-puJAJj82Kn05wpw
  lic: '<div class="footerMax560"><p>博客内容遵循 <a target="_blank" rel="external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">「署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)」</a> 协议</p></div>'
  cpy: '<div class="footerMax490">Copyright 2019 - 2022 SakuraSep. All Rights Reserved</div>'
  me: '<a href="/">上杉九月</a> '
  icp: '<a href="https://beian.miit.gov.cn/#/Integrated/index"><span>鲁ICP备2020049838号-3</span></a>'

# 封面
cover:
  height_scheme: full
  layout_scheme: dock
  display:
    home: true
    archive: true
    others: true
  background: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/Wallpaper/20.jpg
  title: '上杉九月的博客'
  subtitle: '每天醒来，都会充满活力！'
  search: 搜索你想知道的内容...
  features:
    - name: 博客
      url: /
      img: https://cdn.jsdelivr.net/gh/sakurasep/img-cdn@2.0/Twemoji/assets/svg/1f4f0.svg
    - name: 分类
      icon: #
      img: https://cdn.jsdelivr.net/gh/sakurasep/img-cdn@2.0/Twemoji/assets/svg/1f5c3.svg
      url: /categories/
    - name: 标签
      icon: #
      img: https://cdn.jsdelivr.net/gh/sakurasep/img-cdn@2.0/Twemoji/assets/svg/1f5d2.svg
      url: /tags/
    - name: 归档
      icon: #
      img: https://cdn.jsdelivr.net/gh/sakurasep/img-cdn@2.0/Twemoji/assets/svg/1f5de.svg
      url: /archives/
    - name: 友链
      img: https://cdn.jsdelivr.net/gh/sakurasep/img-cdn@2.0/Twemoji/assets/svg/1f4e2.svg
      url: /friends/
    - name: 关于
      icon: #
      img: https://cdn.jsdelivr.net/gh/sakurasep/img-cdn@2.0/Twemoji/assets/svg/1f5a5.svg
      url: /about/

# 文章
article:
  preview:
    line_style: hidden
    pin_icon: https://cdn.jsdelivr.net/gh/sakurasep/img-cdn@2.0/Twemoji/assets/svg/1f4cc.svg
  body:
    top_meta: [author, wordcount, category, updated, counter]
    bottom_meta: [category, tags, updated, share]
    meta_library:
      author:
        avatar: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/touxiang.jpg
        name: 上杉九月
        url: /
      date:
        icon: fa-light fa-calendar-alt BELIZEHOLE faa-vertical
      updated:
        icon: fa-light fa-edit WISTERIA faa-vertical
      category:
        icon: fa-light fa-folder-open EMERALD faa-vertical
      counter:
        icon: fa-light fa-eye SUNFLOWER faa-vertical
      walinecount:
        icon: fa-light fa-comment-dots SUNFLOWER faa-vertical
      wordcount:
        icon_wordcount: fa-light fa-keyboard EMERALD
        icon_duration: fa-light fa-hourglass-half EMERALD
      tags:
        icon: fa-light fa-hashtag EMERALD
      share:
        - id: qq
          img:  volantis-static/media/org.volantis/logo/128/qq.png 
        - id: qzone
          img: volantis-static/media/org.volantis/logo/128/qzone.png 
        - id: weibo
          img: volantis-static/media/org.volantis/logo/128/weibo.png 
        - id: qrcode 
          img: volantis-static/media/org.volantis/logo/128/wechat.png 
        - id: telegram
          img: volantis-static/media/org.volantis/logo/128/telegram.png
    footer_widget:
      related_posts:
        enable: true
        icon: fa-light fa-bookmark WISTERIA faa-vertical
        placeholder_img: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/upload.jpg
      references:
        icon: fa-light fa-quote-left WISTERIA faa-vertical
      copyright:
        enable: true
        content:
          - '博客内容遵循 <a href="/page/cc">署名-相同方式共享 4.0 国际 (CC BY-SA 4.0)</a> 协议。'
      donate:
        enable: true
        images: 
          - https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/AliPay.png
          - https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/Wechat.png


# 第三方插件
plugins:
  # issues api
  sitesjs:
    enable: true
  friendsjs:
    enable: true
  contributorsjs:
    enable: true

  fontawesome: https://cdn.jsdelivr.net/gh/inkss/fontawesome@6.0.0/css/all.min.css
  fontawesome_animation:
    enable: true

  preload:
    enable: true
    service: instant_page

  aplayer:
    enable: true
    id: 2768120286

  parallax:
    enable: true
    position: fixed      
    duration: 0       
    fade: 1500            
    images:
      - https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/Wallpaper/15.jpg

  scrollreveal:
    enable: true

  wordcount:
    enable: true

  comment_typing:
    enable: true

  pjax:
    banUrl:              
       - '/bb/'    
       - '/artitalk/'

  darkmode:
    enable: true

  bbtalk:
    js: https://unpkg.com/bbtalk@0.1.5/dist/bbtalk.js
    appId: w69Q3H9ULXStdK6VmTfNxI2T-MdYXbMMI
    appKey: ug5wcVHclRzU1jeNf6m7yAoN
    serverURLs: https://w69Q3H9U.api.lncldglobal.com

  artitalk:
    js: https://unpkg.com/artitalk
    appId: a48J9aEbfVNsKjoXYMDUN6Lc-MdYXbMMI
    appKey: TRl1pnzSlI9WhOCCKqs7NFqL


  fcircle:
    api: 'https://hexo-circle-of-friends-sakurasep.vercel.app/'
    message: '连接中'



# 侧边栏
sidebar:
  position: left
  for_page: [blogger, notice, navigation , webinfo, lastupdate]
  for_post: [toc, webinfo]
  widget_library:
    blogger:
      display: [desktop]
      avatar: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/touxiang.jpg
      shape: circle
      title: 上杉九月
      subtitle: New Dream New Start
      jinrishici: false
      social:
    toc:
      class: toc
      header:
        icon: fa-light fa-list SUNFLOWER faa-vertical
        title: 本文目录
      min_depth: 1
      max_depth: 6

    category:
      header:
        icon: fa-light fa-folder-open SUNFLOWER faa-vertical

    tagcloud:
      header:
        icon: fa-light fa-tags SUNFLOWER faa-vertical

    webinfo:
      header:
        icon: fa-light fa-award SUNFLOWER faa-vertical
      type:
        runtime:
          data: '2019/07/27' 
        visitcounter:
          service: leancloud

    lastupdate:
      header:
        icon: fa-light fa-clock WISTERIA faa-vertical
    
    notice:
      class: text
      display: [desktop]
      header:
        icon: fa-light fa-ghost PETERRIVE faa-vertical
        title: 本站公告
      content:
        - '你好，欢迎访问我的个人博客'
        - '本博客内容大多数为学习记录和科技向相关。'
        - '[上杉九月的博客-Typecho](https://blog.sakurasep.club/)'
        - '[九月的生活-Halo](https://halo.sakurasep.club/)'
    
    navigation:
      class: grid
      display: [desktop]
      header:
        icon: fal fa-map-signs POMEGRANATE 
        title: 站内导航
      fixed: true 
      rows:
        - name: 留言板
          icon: fal fa-comments-alt GREENSEA faa-ring faa-slow
          url:  /info/
        - name: 关于本站
          icon: fal fa-drafting-compass NEPHRITIS faa-ring faa-slow
          url: /about/  
        - name: 博主说说
          icon: fal fa-history POMEGRANATE faa-ring faa-slow
          url: /bb/
        - name: 番剧推荐
          icon: fal fa-film-alt WISTERIA faa-ring faa-slow
          url: /bangumis/
        - name: 小伙伴们
          icon: fal fa-stamp CONCRETE faa-ring faa-slow
          url: /friends/
        - name: 开往
          icon: fal fa-subway PETERRIVE faa-ring faa-slow
          url: https://travellings.link

# 展位图
default:
  avatar: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/avatar.svg
  link: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/link.svg
  cover: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/cover.svg
  image: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5199/static/icon/image.svg

# 评论
comments:
  title: <i class='fa-light fa-comments POMEGRANATE'></i> 评论
  service: twikoo 
  twikoo:
    js: https://cdn.staticfile.org/twikoo/1.5.11/twikoo.all.min.js
    envId: twikoo-8g109qz0365c3388

# CSP
csp:
  enable: true

# 标签note
tag_plugins:
  note:
    iconfont: 'Font Awesome 6 Pro'

# 数据分析
analytics:
  leancloud: 
    app_id: 6AlMmDb6FMNtaNh3XlKYsizU-MdYXbMMI
    app_key: jTB2tRPg1t2zVKxnRvrD0lYn


# HPP Talk
hpptalk:
  enable: true
  domain: hpp.sakurasep.site
  path:
  limit:
  start:
  js:
  css:
  option:
  front_matter: